<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="mass" value="0.05" /> <!-- arbitrary value for mass -->
  <xacro:property name="height" value="0.07" /> <!-- z axis -->
  <xacro:property name="width" value="0.07" /> <!-- width  is along the x axis -->
  <xacro:property name="deep" value="0.05" /> <!-- y axis -->
  <xacro:property name="finger_height" value="0.045" /> <!-- z axis -->
  <xacro:property name="finger_width" value="0.03" /> <!-- width  is along the x axis -->
  <xacro:property name="finger_deep" value="0.025" /> <!-- y axis -->
  <xacro:property name="closing_width" value="0.03" /> <!-- distance between the fingers when closed -->

  <!-- This offset is due to avoid the collision between the gripper and the end effector "boundary"-->
  <xacro:property name="offset" value="0.0051" /> 

  <xacro:macro name="grippertcp" params="prefix parent">

    <link name="${prefix}_link_gripper_tcp" />
    
    <joint name="${prefix}_joint_gripper_tcp" type="fixed" >
      <parent link="${parent}" />
      <child link="${prefix}_link_gripper_tcp" />
      <origin xyz="0.0 0.0 0.115" rpy="0 0 0" />
    </joint>

    <joint name="${prefix}_joint_gripper_base_tcp" type="fixed" >
      <parent link="${parent}" />
      <child link="${prefix}_link_gripper_base_tcp" />
      <origin xyz="0.0 0.0 ${height/2 + offset/2}" rpy="0 0 0" />
    </joint>

    <joint name="${prefix}_joint_gripper_left_finger_tcp" type="fixed" >
      <parent link="${prefix}_link_gripper_base_tcp" />
      <child link="${prefix}_link_gripper_left_finger_tcp" />
      <origin xyz="${closing_width/2 + finger_width/2} 0.0 ${height/2}" rpy="0 0 0" />
    </joint>

    <joint name="${prefix}_joint_gripper_right_finger_tcp" type="fixed" >
      <parent link="${prefix}_link_gripper_base_tcp" />
      <child link="${prefix}_link_gripper_right_finger_tcp" />
      <origin xyz="${-closing_width/2 - finger_width/2} 0.0 ${height/2}" rpy="0 0 0" />
    </joint>

    <link name="${prefix}_link_gripper_base_tcp">
		<collision>
	      <origin xyz="0 0 0" rpy="0 0 0"/>
	      <geometry>
		<box size="${width} ${deep} ${height -offset}"/>
	      </geometry>
	    </collision>

	    <visual>
	      <origin xyz="0 0 0" rpy="0 0 0"/>
	      <geometry>
		<box size="${width} ${deep} ${height -offset}"/>
	      </geometry>
	      <material name="white"/>
	    </visual>

	    <inertial>
	      <origin xyz="0 0 0" rpy="0 0 0"/>
	      <mass value="${mass}"/>
	      <inertia
		  ixx="${mass / 12.0 * (deep*deep + height*height)}" ixy="0.0" ixz="0.0"
		  iyy="${mass / 12.0 * (width*width + height*height)}" iyz="0.0"
		  izz="${mass / 12.0 * (width*width + deep*deep)}"/>
	    </inertial>
  	</link>

    <link name="${prefix}_link_gripper_right_finger_tcp">
		<collision>
	      <origin xyz="0 0 ${finger_height/2}" rpy="0 0 0"/>
	      <geometry>
		<box size="${finger_width} ${finger_deep} ${finger_height}"/>
	      </geometry>
	    </collision>

	    <visual>
	      <origin xyz="0 0 ${finger_height/2}" rpy="0 0 0"/>
	      <geometry>
		<box size="${finger_width} ${finger_deep} ${finger_height}"/>
	      </geometry>
	      <material name="white"/>
	    </visual>

	    <inertial>
	      <origin xyz="0 0 ${finger_height/2}" rpy="0 0 0"/>
	      <mass value="${mass}"/>
	      <inertia
		  ixx="${mass / 12.0 * (finger_deep*finger_deep + finger_height*finger_height)}" ixy="0.0" ixz="0.0"
		  iyy="${mass / 12.0 * (finger_width*finger_width + finger_height*finger_height)}" iyz="0.0"
		  izz="${mass / 12.0 * (finger_width*finger_width + finger_deep*finger_deep)}"/>
	    </inertial>
  	</link>

  	<link name="${prefix}_link_gripper_left_finger_tcp">
		<collision>
	      <origin xyz="0 0 ${finger_height/2}" rpy="0 0 0"/>
	      <geometry>
		<box size="${finger_width} ${finger_deep} ${finger_height}"/>
	      </geometry>
	    </collision>

	    <visual>
	      <origin xyz="0 0 ${finger_height/2}" rpy="0 0 0"/>
	      <geometry>
		<box size="${finger_width} ${finger_deep} ${finger_height}"/>
	      </geometry>
	      <material name="white"/>
	    </visual>

	    <inertial>
	      <origin xyz="0 0 ${finger_height/2}" rpy="0 0 0"/>
	      <mass value="${mass}"/>
	      <inertia
		  ixx="${mass / 12.0 * (finger_deep*finger_deep + finger_height*finger_height)}" ixy="0.0" ixz="0.0"
		  iyy="${mass / 12.0 * (finger_width*finger_width + finger_height*finger_height)}" iyz="0.0"
		  izz="${mass / 12.0 * (finger_width*finger_width + finger_deep*finger_deep)}"/>
	    </inertial>
  	</link>

  </xacro:macro>

</robot>
