sensor_msgs/PointCloud2 original_cloud
sensor_msgs/PointCloud2[] segmented_objects
iri_tos_supervoxels/plane_coefficients plane_coefficients
---
iri_table_clearing_predicates/BlockPredicate[] block_predicates
iri_table_clearing_predicates/BlockGraspPredicate[] block_grasp_predicates
iri_table_clearing_predicates/OnTopPredicate[] on_top_predicates
iri_table_clearing_predicates/PushingDirections[] objects_pushing_directions
iri_table_clearing_predicates/GraspingPoses[] grasping_poses
iri_table_clearing_predicates/GraspingPoses[] approaching_poses
iri_table_clearing_predicates/PushingPoses[] pushing_poses
iri_table_clearing_predicates/AABB[] aabbs
geometry_msgs/Point[] centroids
iri_table_clearing_predicates/PrincipalDirections[] principal_directions
float32 pushing_object_distance
iri_table_clearing_predicates/PushingLength[] pushing_lengths
iri_table_clearing_predicates/PushingGraspingPose[] pushing_grasping_poses


# times for experiments data
float32 on_predicates_time
float32 block_predicates_time
float32 block_grasp_predicates_time
float32 objects_collisions_time
float32 ee_collisions_time
float32 average_objects_collision_time
float32 average_ee_collision_time