controller_manager_ns: moveit_simple_controller_manager
controller_list:
  - name: estirabot/estirabot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - estirabot_joint_1
      - estirabot_joint_2
      - estirabot_joint_3
      - estirabot_joint_4
      - estirabot_joint_5
      - estirabot_joint_6
      - estirabot_joint_7
