geometry_msgs/PoseStamped[] pushing_cartesian_trajectory 
geometry_msgs/PoseStamped future_pre_grasp_pose
geometry_msgs/PoseStamped future_grasp_pose
geometry_msgs/PoseStamped future_post_grasp_pose
--- 
bool success
float32 ik_time
float32 execution_time